// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh5RAYWwSGlqifRTtiFdtRnyPbXA_Pai4',
    appId: '1:672143718507:web:8c9ee5e690aaa3855c192e',
    messagingSenderId: '672143718507',
    projectId: 'e-commerce-8b008',
    authDomain: 'e-commerce-8b008.firebaseapp.com',
    storageBucket: 'e-commerce-8b008.appspot.com',
    measurementId: 'G-GD9KW20PQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFo14xiyUTmWSgn0CIFAxOSb14vpYiWwM',
    appId: '1:672143718507:android:278fb34a02911c4a5c192e',
    messagingSenderId: '672143718507',
    projectId: 'e-commerce-8b008',
    storageBucket: 'e-commerce-8b008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6PkPR-stBGkI_Pa_xBsp0oflw6I4t3k',
    appId: '1:672143718507:ios:6faa60d8f0dfb72f5c192e',
    messagingSenderId: '672143718507',
    projectId: 'e-commerce-8b008',
    storageBucket: 'e-commerce-8b008.appspot.com',
    iosClientId: '672143718507-7878rh8sj8agf930f5h7sgrtqs2r7tvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6PkPR-stBGkI_Pa_xBsp0oflw6I4t3k',
    appId: '1:672143718507:ios:6faa60d8f0dfb72f5c192e',
    messagingSenderId: '672143718507',
    projectId: 'e-commerce-8b008',
    storageBucket: 'e-commerce-8b008.appspot.com',
    iosClientId: '672143718507-7878rh8sj8agf930f5h7sgrtqs2r7tvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
